name: Deploy to EC2

on:
  push:
    branches: [ "Development" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build Docker image
        run: docker build -t scout-management .

      - name: Save Docker image as tar
        run: docker save scout-management > scout-management.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: scout-management.tar
          target: /home/${{ secrets.EC2_USER }}/

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "==== Running containers ===="
            docker ps -a
            echo "==== Images ===="
            docker images
            echo "==== Running docker processes ===="
            ps aux | grep docker
            echo "==== Attempting normal deployment ===="
            docker load < scout-management.tar
            docker stop scout-management || true
            docker rm scout-management || true
            docker run --name scout-management -e DB_HOST=${{ secrets.DB_HOST }} -e EC2_HOST=${{ secrets.EC2_HOST }} -e USER_DB=${{ secrets.USER_DB }} -e PASSWORD_DB=${{ secrets.PASSWORD_DB }} -e DB_NAME_SCOUT=${{ secrets.DB_NAME_SCOUT }} -e EMAIL_SCOUT=${{ secrets.EMAIL_SCOUT }} -e PASSWORD_APP_EMAIL="fjko feme rrcu ixdd" -p 8080:8080 scout-management:latest