name: SonarCloud analysis

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-latest

    env:
      DB_HOST: localhost:3306
      DB_NAME_SCOUT: scoutmanagementdb
      USER_DB: root
      PASSWORD_DB: roottoor
      EMAIL_SCOUT: jaguaresscoutmanagement@gmail.com
      PASSWORD_APP_EMAIL: fjko feme rrcu ixdd

      services:
        mysql:
          image: mysql:8
          ports:
            - 3306:3306
          env:
            MYSQL_ROOT_PASSWORD: roottoor
            MYSQL_DATABASE: scoutmanagementdb
          options: >-
            --health-cmd="mysqladmin ping --silent"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean verify

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.ORGANIZATION_KEY }}
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
